jdbc:
  driver: com.mysql.jdbc.Driver

spring:
  profiles:
    active: profile
    
---

spring:
  profiles: profile
jdbc:
  url: jdbc:mysql://localhost:3306/jpasample
  username: jpa
  password: sample
